### ISSUE TITLE
ConvergenceWarning

### ISSUE THREAD

**Issue by shazhendong** [w4k2/problexity#2]
When I try to investigate the complexity of dataset from `X, y = load_breast_cancer(return_X_y=True)`, I will receive warning messages as follows:
`/Users/randomUserName/opt/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(`

**Comment by tentato** [comment]
Explained in the readme file

**Comment by shazhendong** [comment]
Thank you!
