### ISSUE TITLE
calculate only f1 complexity measure

### ISSUE THREAD

**Issue by wal-iston** [w4k2/problexity#7]
Hi, it sounds that you can initialize an object from class ComplexityCalculator passing a parameter metrics as in line 81 of ComplexityCalculator.py. But it updata self.metrics with C_METRICS as in line 104.

I was wondering if I could fit data only for f1 complexity measure, for example.

Thanks

**Comment by JKomorniczak** [comment]
Hi, 
you can calculate a single measure by directly calling function problexity.classification.f1(X, y). 
If you wish to do so via ComplexityCalculator (for example in case of multi-class data, to easily handle OVA/OVO binarization strategy) you would need to provide the following hyperparameters to the class constructor:
C_METRICS = [f1]
C_COLORS = ['#FD0100']
C_RANGES = {'FB': 1}
C_WEIGHTS = np.ones((1))

Hope this helps
